# Generated by Django 5.0.4 on 2024-04-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='Taom nomi')),
                ('food_recipe', models.TextField(blank=True, default='Kiritilmagan !', null=True, verbose_name='Taomning retsepti')),
                ('food_preparation', models.TextField(blank=True, null=True, verbose_name='Taomning tayyorlanishi')),
                ('food_price', models.FloatField(verbose_name='Narxi')),
                ('food_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uzbek_cuisine.category', verbose_name='Taom turi')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'db_table': 'food',
            },
        ),
    ]
